language: generic
sudo: required
dist: trusty
notifications:
  email: false
matrix:
  include:
    - os: osx
      osx_image: xcode9
      script:
        - make LIB_DIR=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib

    - os: osx
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0.2
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - make LIB_DIR=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib

    - os: osx
      osx_image: xcode9
      env:
        - SWIFT_VERSION=4.0.3
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - make LIB_DIR=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/lib

    - os: linux
      env:
        - SWIFT_VERSION=4.0
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.swiftenv/versions/$SWIFT_VERSION/usr/lib
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build -Xlinker -l:sourcekitdInProc -c release
    - os: linux
      env:
        - SWIFT_VERSION=4.0.2
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.swiftenv/versions/$SWIFT_VERSION/usr/lib
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build -Xlinker -l:sourcekitdInProc -c release

    - os: linux
      env:
        - SWIFT_VERSION=4.0.3
        - LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HOME/.swiftenv/versions/$SWIFT_VERSION/usr/lib
      install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - echo $LD_LIBRARY_PATH
        - ls $HOME/.swiftenv/versions/$SWIFT_VERSION/usr/lib
        - swift build -Xlinker -l:sourcekitdInProc -c release
